/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
 * Generated on: 20-Mar-2016 14:25:18
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 4
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Values used to the FIR filter
 *
 * Expected path to tmwtypes.h 
 * C:\Matlab 2015b\extern\include\tmwtypes.h 
 */
#define M  4
/* Constants made from FDATOOL in matlab. Used in the FIR-filter */
float B[4] = {
   -0.09641229823382,   0.5875566212925,   0.5875566212925, -0.09641229823382
};
